### PR TITLE
change small icon of notification to use the foreground icon only

### LINKED ISSUE #6: Notification Icon is a blank round icon on Phone
Since Android 6, icons on status bar are shown in white/black and transparent. Icons with non-transparent are shown as a blank square or circle. As it's shown in the play store, LineNotificationSupport doesn't fully embrace the new design.
Screenshot 2023-10-17 at 10 56 04

The issue stops `LINE Notification Management` from working properly. An clean and clear icon would help replacing LINE notifications a better experience.

I am working on a PR to use the [foreground icon](https://github.com/rickwangtw/LineNotificationSupport/blob/main/app/src/main/res/drawable/ic_launcher_foreground.xml) as the notification icon.

Any idea?

### PR DESCRIPTION
**Pull request by inkybr**
The PR aims to fix #6 so a clear icon will be shown on status bar.

It adds a notification icon resource, `ic_new_message` from a trimmed `drawable/ic_launcher_foreground.xml` and update the SmallIcon of Notification Builders. 

Results on Pixel 8 Android 14

Screenshot_20231018-171002

Screenshot_20231018-165138

### CODE REVIEW

**Comment by inkybr** [comment]
The icon looks too dense for a status bar icon, so I have two other icon modified from the original one. It would be great if we can use one of them.

Moving `LINE` to the watch
Screenshot_20231018-173224
Screenshot_20231018-173232

Remove `LINE` because it could be barely recognized on status bar.
Screenshot_20231018-174409
Screenshot_20231018-174413

**Comment by inkybr** [comment]
@rickwangtw can you look at this please? Thanks!

**Comment by rickwangtw** [comment]
This looks awesome! Thanks for your contribution!
I really like the 3rd option you've suggested, but I don't see that in the pull request. Am I missing something?

**Comment by rickwangtw** [comment]
Also, thanks for pointing this out. I have no idea that there are specific requirements with the icons. 
Frustrating that those aren't in official notification docs and I have to learn it through Stackoverflow regarding the details.

https://stackoverflow.com/questions/28387602/notification-bar-icon-turns-white-in-android-5-lollipop

**Comment by inkybr** [comment]
@rickwangtw Glad you like it. I update the PR to replace the icon with the third one.

**Pull request merged**
